### ISSUE TITLE
Home Assistant YAML config

### ISSUE THREAD

**Issue by tiagofreire-pt** [mezz64/pyTVHeadend#1]
Hi.

Is this the correct config schema?

```yaml
tvheadend:
  host: 192.168.10.68
  port: 9981
  username: XXXXXX
  password: YYYYY
  maxconn: '2'
```

Thanks.

**Comment by kuchel77** [comment]
I haven't got it setup as yet, but just by looking at the code I think it should be

```yaml
sensor:
  - platform: tvheadend
    host: 192.168.10.68
```

and so on.

The other issue you might have, is that all of the code from custom_components, should be in a directory called tvheadend to ensure it is consistent and loaded from memory. So /config/custom_components/tvheadend/sensor.py for instance should be there, rather than just /config/custom_components.

**Comment by kuchel77** [comment]
```yaml
tvheadend:
  host: 192.168.0.2
  port: 9981
  maxconn: '2'
```
This connects to my server, but because I haven't got it properly setup at the moment, that is all that works.
